"""Admin CRM persistence helpers for AI Hub clients and usage.

This module re-exports functions, classes, and constants from the extracted
domain submodules for backward compatibility.
"""

from __future__ import annotations

# Re-export from schema
from db.core.schema import (
    ADMIN_SCHEMA_SQL,
    _connect,
    init_admin_schema,
)

# Re-export from settings manager
from db.settings.settings_manager import (
    ENV_FILE,
    FLOAT_SETTING_RANGES,
    INTEGER_SETTING_RANGES,
    SECRET_SETTING_KEYS,
    SETTING_KEYS,
    _first_text,
    _masked_value,
    _public_hub_origin,
    _setting_is_configured,
    _setting_runtime_default,
    _setting_text,
    _setting_value,
    _validate_float_range,
    _validate_integer_range,
    _validate_numeric_setting,
    _validated_settings,
    settings_snapshot,
    update_settings,
)

# Re-export from runtime quota
from db.runtime.quota import (
    DEFAULT_CLIENT_TOKEN_LIMIT,
    DEFAULT_SESSION_TOKEN_LIMIT,
    MAX_CLIENT_TOKEN_LIMIT,
    MAX_SESSION_TOKEN_LIMIT,
    TOKEN_CHAR_RATIO,
    TokenQuotaExceededError,
    _client_session_limit,
    _ensure_conversation_session,
    _quota_part,
    _session_token_total,
    _usage_summary,
    assert_usage_allowed,
    estimate_tokens,
    quota_status,
)

# Re-export from analytics metrics
from db.analytics.metrics import (
    ANALYTICS_DEFAULT_RANGE,
    LATENCY_ACCEPTABLE_MS,
    LATENCY_FAST_MS,
    PERCENT_SCALE,
    RANGE_DAYS,
    SUMMARY_MAX_BULLETS,
    _average_latency,
    _clean_range_key,
    _clean_summary_bullets,
    _clean_summary_line,
    _counter_rows,
    _daily_series,
    _demand_summary_bullet,
    _heuristic_summary,
    _latency_bucket_rows,
    _latency_summary_bullet,
    _peak_series_day,
    _percent,
    _range_start,
    _row_tokens,
    _stock_summary_bullet,
    _usage_rows,
    _conversation_turn,
    analytics_snapshot,
    conversation_log,
    generate_analytics_summary,
    json_ready_analytics,
)
from db.analytics.products import (
    ANALYTICS_CATALOG_PRODUCT_LIMIT,
    ANALYTICS_STOPWORDS,
    PRODUCT_COMMON_TOKEN_MIN_COUNT,
    PRODUCT_COMMON_TOKEN_RATIO,
    PRODUCT_FULL_MATCH_WEIGHT,
    PRODUCT_TOKEN_MATCH_WEIGHT,
    PRODUCT_TOKEN_STOPWORDS,
    PRODUCT_TYPE_TOKENS,
    _catalog_product_names,
    _common_product_tokens,
    _customer_demand_text,
    _exact_product_matches,
    _fallback_product_matches,
    _is_product_signal_token,
    _normalized_product_text,
    _normalized_product_tokens,
    _product_matchers,
    _product_matchers_by_site,
    _significant_product_tokens,
    _singular_token,
    _unique_product_names,
    top_product_mentions as _top_product_mentions,
)

# Re-export from clients
from db.client_domain.client_facade import (
    CLIENT_STATUS_AVAILABLE,
    CLIENT_STATUS_DELETED,
    CLIENT_STATUS_DISABLED,
    CLIENT_STATUS_LIVE,
    CRAWL_STATUS_ERROR,
    CRAWL_STATUS_NOT_STARTED,
    CRAWL_STATUS_RUNNING,
    CRAWL_STATUS_OK,
    SETUP_STATUS_CANCELED,
    SETUP_STATUS_RUNNING,
    SETUP_STATUS_TIMED_OUT,
    DEFAULT_ADAPTER_NAME,
    DEFAULT_CLIENT_COMPLIANCE_MODE,
    DEFAULT_CLIENT_LOCALE,
    DEFAULT_CLIENT_PANEL_PASSWORD,
    DEFAULT_CLIENT_VERTICAL_KEY,
    DEFAULT_PLAN,
    DEFAULT_USAGE_LIMIT,
    GENERATED_PANEL_PASSWORD_BYTES,
    MIN_CLIENT_PANEL_PASSWORD_LENGTH,
    PANEL_PASSWORD_DISABLED,
    PANEL_PASSWORD_ITERATIONS,
    PANEL_PASSWORD_SALT_BYTES,
    SESSION_ID_MAX_LENGTH,
    SITE_ID_MAX_LENGTH,
    DEFAULT_DEPLOY_MODE,
    _b64,
    _category_count,
    _client_row,
    _client_summary,
    _empty_catalog_summary,
    _hash_panel_password,
    _health_snapshot,
    _latest_sync,
    _origin_from_url,
    _panel_password_configured,
    _panel_password_status,
    _postgres_health,
    _recent_usage_events,
    _required_text,
    _safe_catalog_preview,
    _safe_catalog_summary,
    _safe_answer_cache_summary,
    _safe_session_id,
    _safe_site_id,
    _safe_sync_history,
    _set_default_panel_password,
    _site_id_from_name,
    _unb64,
    _update_client_status,
    _validated_url,
    _verify_panel_password,
    activate_client,
    create_client,
    cleanup_synthetic_demo_clients,
    discover_available_client,
    ensure_default_client,
    expire_stale_client_initialization_runs,
    generate_client_panel_password,
    get_client_detail,
    get_latest_crawl_report,
    get_readiness_report,
    get_site_selectors,
    get_client_vertical_key,
    get_vertical_detail,
    is_client_widget_enabled,
    list_clients,
    list_client_action_events,
    list_verticals,
    move_client_to_available,
    record_usage_event,
    record_audit_event,
    refresh_client_action_proposals,
    review_client_action_candidate,
    review_client_action_proposal,
    review_client_flow_repair_proposal,
    overview,
    remove_client,
    request_client_setup_cancel,
    revoke_client_panel_password,
    save_adapter_validation_report,
    save_client_assistant_smoke_report,
    save_client_action_event,
    save_client_flow_report,
    save_client_initialization_report,
    save_client_interaction_event,
    save_client_policy_event,
    save_client_rehearsal_report,
    save_client_regression_report,
    save_crawl_report,
    save_readiness_report,
    save_site_selectors,
    set_client_enabled,
    setup_cancel_requested,
    update_client_adapter_actions,
    update_client_crawl_status,
    update_client_discovery_config,
    update_client_panel_password,
    update_client_session_token_limit,
    update_client_setup_status,
    update_client_token_limits,
    update_client_vertical,
    verify_client_panel_password,
    script_tag_for_site,
)

# Re-export from prompts
from db.prompting.prompt_profiles import (
    PROMPT_STATUS_ARCHIVED,
    PROMPT_STATUS_DRAFT,
    PROMPT_STATUS_PUBLISHED,
    ensure_client_prompt_profile,
    get_client_prompt_profile,
    list_prompt_profiles,
    prompt_profile_context,
    publish_prompt_version,
    save_client_prompt_profile,
)
