export const ACTIONS = Object.freeze({
  ADD_TO_CART: "ADD_TO_CART",
  CHECKOUT: "CHECKOUT",
  CHECKOUT_HANDOFF: "CHECKOUT_HANDOFF",
  CHECK_APPOINTMENT_AVAILABILITY: "CHECK_APPOINTMENT_AVAILABILITY",
  CHECK_AVAILABILITY: "CHECK_AVAILABILITY",
  CHECK_DELIVERY_AVAILABILITY: "CHECK_DELIVERY_AVAILABILITY",
  CHECK_ELIGIBILITY_SOFT: "CHECK_ELIGIBILITY_SOFT",
  CHECK_PREREQUISITES: "CHECK_PREREQUISITES",
  CLEAR_CART: "CLEAR_CART",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  CLEAR_HISTORY: "CLEAR_HISTORY",
  BUILD_ITINERARY: "BUILD_ITINERARY",
  BUILD_LEARNING_PATH: "BUILD_LEARNING_PATH",
  CAPTURE_LEAD: "CAPTURE_LEAD",
  CAPTURE_PATIENT_LEAD: "CAPTURE_PATIENT_LEAD",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",
  FILTER_ENTITIES: "FILTER_ENTITIES",
  COMPARE_ENTITIES: "COMPARE_ENTITIES",
  CONTACT_AGENT: "CONTACT_AGENT",
  HANDOFF_TO_ADVISOR: "HANDOFF_TO_ADVISOR",
  HANDOFF_TO_AGENT: "HANDOFF_TO_AGENT",
  HANDOFF_TO_CLINIC: "HANDOFF_TO_CLINIC",
  HANDOFF_TO_HUMAN: "HANDOFF_TO_HUMAN",
  HANDOFF_TO_LAWYER: "HANDOFF_TO_LAWYER",
  HANDOFF_TO_LICENSED_AGENT: "HANDOFF_TO_LICENSED_AGENT",
  HANDOFF_TO_RECRUITER: "HANDOFF_TO_RECRUITER",
  JOIN_WAITLIST: "JOIN_WAITLIST",
  MATCH_JOBS: "MATCH_JOBS",
  NAVIGATE_TO: "NAVIGATE_TO",
  OPEN_CLAIM_FLOW: "OPEN_CLAIM_FLOW",
  OPEN_CONTACT: "OPEN_CONTACT",
  OPEN_DISCLOSURE: "OPEN_DISCLOSURE",
  OPEN_ENTITY_DETAIL: "OPEN_ENTITY_DETAIL",
  OPEN_LOCATION: "OPEN_LOCATION",
  OPEN_MAP: "OPEN_MAP",
  OPEN_POLICY: "OPEN_POLICY",
  OPEN_PROJECTS: "OPEN_PROJECTS",
  OPEN_RENEWAL_FLOW: "OPEN_RENEWAL_FLOW",
  OPEN_SERVICES: "OPEN_SERVICES",
  OPEN_SYLLABUS: "OPEN_SYLLABUS",
  OPEN_TELECONSULT: "OPEN_TELECONSULT",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REQUEST_APPOINTMENT: "REQUEST_APPOINTMENT",
  REQUEST_CALLBACK: "REQUEST_CALLBACK",
  REQUEST_CONSULTATION: "REQUEST_CONSULTATION",
  REQUEST_COUNSELOR_CALLBACK: "REQUEST_COUNSELOR_CALLBACK",
  REQUEST_ESTIMATE: "REQUEST_ESTIMATE",
  REQUEST_SITE_VISIT: "REQUEST_SITE_VISIT",
  REQUEST_TEST_DRIVE: "REQUEST_TEST_DRIVE",
  REQUEST_VIEWING: "REQUEST_VIEWING",
  RUN_DOM_SEQUENCE: "RUN_DOM_SEQUENCE",
  RUN_AFFORDABILITY_CALCULATOR: "RUN_AFFORDABILITY_CALCULATOR",
  RUN_CALCULATOR: "RUN_CALCULATOR",
  SAVE_SEARCH: "SAVE_SEARCH",
  SCHEDULE_ORDER: "SCHEDULE_ORDER",
  SEARCH_AVAILABILITY: "SEARCH_AVAILABILITY",
  SET_LOCATION: "SET_LOCATION",
  SHOW_COMPARISON: "SHOW_COMPARISON",
  SHOW_EMERGENCY_NOTICE: "SHOW_EMERGENCY_NOTICE",
  SHOW_ENTITIES: "SHOW_ENTITIES",
  SHOW_PRODUCT_DETAIL: "SHOW_PRODUCT_DETAIL",
  SHOW_PRODUCTS: "SHOW_PRODUCTS",
  SORT_ENTITIES: "SORT_ENTITIES",
  SORT_PRODUCTS: "SORT_PRODUCTS",
  START_APPLICATION: "START_APPLICATION",
  START_BOOKING: "START_BOOKING",
  START_ENROLLMENT: "START_ENROLLMENT",
  START_INTAKE: "START_INTAKE",
  START_QUOTE: "START_QUOTE",
  START_TICKET_PURCHASE: "START_TICKET_PURCHASE",
  UPDATE_CART_QUANTITY: "UPDATE_CART_QUANTITY",
  UPDATE_PREFERENCES: "UPDATE_PREFERENCES",
  BOOK_APPOINTMENT_REQUEST: "BOOK_APPOINTMENT_REQUEST",
});

export const ACTION_PARAMS = Object.freeze({
  ENTITY_ID: "entity_id",
  ENTITY_IDS: "entity_ids",
  MESSAGE: "message",
  PAGE: "page",
  PRODUCT_ID: "product_id",
  PRODUCT_IDS: "product_ids",
  QUANTITY: "quantity",
  REASON: "reason",
  SEARCH_QUERY: "search_query",
  URL: "url",
});

export const CART_PAGE_TARGETS = new Set(["cart", "/cart"]);
export const DEFAULT_RECOMMENDATION_TITLE = "Recommended products";
export const DEFAULT_ENTITY_RECOMMENDATION_TITLE = "Relevant options";

export const API_PATHS = Object.freeze({
  KNOWLEDGE_BY_IDS: "/v1/knowledge/by-ids",
  PRODUCTS_BY_IDS: "/v1/products/by-ids",
  SHOP: "/v1/shop",
  SHOP_WS: "/v1/ws/shop",
  WIDGET_STATUS: "/v1/widget/status",
});

export const AUDIO = Object.freeze({
  DATA_WAV_PREFIX: "data:audio/wav;base64,",
  WEBM_FILENAME: "audio.webm",
  WEBM_MIME_TYPE: "audio/webm",
});

export const HTTP_METHODS = Object.freeze({
  POST: "POST",
});

export const STATUS = Object.freeze({
  ERROR: "error",
  PROCESSING: "processing",
  READY: "ready",
  RECORDING: "recording",
});

export const CONVERSATION_HISTORY_LIMIT = 12;
export const DEFAULT_VISIBLE_RESET_DELAY_MS = 2400;
export const AUTO_GREETING_DELAY_MS = 900;
export const AUTO_GREETING_VISIBLE_MS = 4200;
export const DEFAULT_CART_QUANTITY = 1;
export const OVERLAY_COLLAPSE_DELAY_MS = 180;
export const WIDGET_STATUS_POLL_INTERVAL_MS = 3000;

export const EVENTS = Object.freeze({
  SHOPBOT_ACTION: "shopbot:action",
});

export const WS_CONNECT_TIMEOUT_MS = 2500;

export const WS_MESSAGES = Object.freeze({
  AUDIO_CHUNK: "audio_chunk",
  AUDIO_END: "audio_end",
  CONFIG: "config",
  DONE: "done",
  ERROR: "error",
  TEXT_CHUNK: "text_chunk",
  TRANSCRIPT: "transcript",
});
